<?php
	include('conn.php');
	$id=$_GET['id'];
	$ss=$_POST['sstation'];
	$es=$_POST['estation'];
	$tn=$_POST['tn'];
	$jd=$_POST['jd'];
	$firstname=$_POST['firstname'];
	$lastname=$_POST['lastname'];
    $age=$_POST['age'];
    $gender=$_POST['gender'];
    $coach=$_POST['coach'];
    $seat=$_POST['seat'];
	$f=fopen("Ticket.txt","a+");
	fwrite($f,"The above person's ticket has been edited Below is new details \n");
	fwrite($f,"Train Ticket\n");
			fwrite($f,"Starting Station :".$ss."\n");
			fwrite($f,"End Station :".$es."\n");
			fwrite($f,"Train name :".$tn."\n");
			fwrite($f,"Journey date :".$jd."\n");
		fwrite($f,"First Name :".$firstname."\n");
		fwrite($f,"Last Name :".$lastname."\n");
		fwrite($f,"Age:".$age."\n");
		fwrite($f,"Gender:".$gender."\n");
		fwrite($f,"Coach:".$coach."\n");
		fwrite($f,"Seat :".$seat."\n");
		fclose($f);
	mysqli_query($conn,"update `user` set firstname='$firstname', lastname='$lastname',age='$age',gender='$gender',coach='$coach',seat='$seat' where userid='$id'");
	header('location:ticket.php');
?>
